title: "Njabulo Shabalala — Cybersecurity Portfolio"
description: "Cybersecurity | Cloud Security | SOC Analysis | Building secure systems in the cloud"
theme: hacker

# Optional settings for nicer metadata
author: "Njabulo Shabalala"
show_downloads: false

# Links (you can add more if you want)
github:
  is_project_page: false

# Social / Contact links (uncomment if you want them shown)
# twitter_username: yourhandle
# linkedin_username: njabulo-shabalala-9216821a3
