title: "Njabulo Shabalala — Cybersecurity Portfolio"
description: "Cybersecurity | Cloud Security | SOC Analysis | Building secure systems in the cloud"
theme: hacker

# Automatic navigation menu
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"

author: "Njabulo Shabalala"
show_downloads: false

# linkedin_username: njabulo-shabalala-9216821a3
